### ISSUE TITLE
Sectioning Codes

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#10]
Every section now begins with either the section symbol+space+number+.+space+word or SEC.+space+number+.+word at the beginning of a line. Any line that begins with TITLE, CHAPTER, ARTICLE, SECTION, DIVISION, or SUBDIVISION is header material and thus the termination of the previous section. 

Anything that does not begin with the section symbol or SEC. could be disregarded or deleted if we want to after chunking.

As for fuzzyiness--SEC. may have upper or lower cases or be mixed, and there may be a few instances where I missed the period. There may also be some instances where I mistook an L or O for a 1 or 0.

**Comment by lmullen** [comment]
Should be fixed.
