### ISSUE TITLE
Dissertation Visual #3: Full Corpus Network Graph

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#19]
I think from all the samples, the best graph will probably be generated by minimum sections = 50, maximum edges = 3.

It's probably best if only the parts of the corpus that have connections display, BUT it would be nice to visually show that Louisiana codes (LA1825 and LA1844) don't connect with anything, nor does the later New York Code (NY1876 and NY1879).

I like the coloring scheme of red = original New York, green = one step removed, etc. We need to color all early New York codes red, though--NY1848, NY1849, NY1850, NY1851, NY1853, and adjust the others accordingly.

**Comment by lmullen** [comment]
I think I've got this all laid out, just have to actually get it into the document.

**Comment by lmullen** [comment]
I think this is basically done other than adjusting the presentation.
