### ISSUE TITLE
Dissertation Visual #4: State Network Graph

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#20]
I want the stripped down version of state-to-state borrowings regardless of year, with maximum connections = 1. (Refer to Slack conversation, your post at 9:37 p.m.

If it's easy for you to overlay that on an actual map, wonderful. If not, just update me on the connections, and I can draw the map in QGIS.

**Comment by lmullen** [comment]
I think this is basically done
