### ISSUE TITLE
Dissertation Visual #6: Spectrogram/Heat Map of NY1850

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#22]
Here I'm looking for the reverse of the previous spectrograms. Rather than illustrate sections BORROWED FROM elsewhere, can we illustrate sections in the original Field Code that GET BORROWED elsewhere, and instead of coloring by where they end up, color based on how many times a particular section appears throughout the corpus?

I expect the beginning of the code will be grey--no one has New York's particular court system, so no one copies the jurisdictional texts, then high heat at the heart of the Code with the Field reforms, slackening off around particular proceedings, some of which will be New York specific, then heating up again towards the end with the code of evidence.

**Comment by lmullen** [comment]
Is this still a thing?
