### ISSUE TITLE
Dissertation visual #7: Spectrogram/Heat Map of LA1844

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#23]
Same query as number 6, only this time the goal is to demonstrate that nobody borrows the text of Louisiana. Wouldn't be surprised if it's completely grey, though it would be nice if a section or two turns up borrowed elsewhere.

**Comment by lmullen** [comment]
I don't think this visualization is worth including. Negative findings can be better expressed in prose. Here are all the sections of LA1844 that are borrowed elsewhere. I've limited this to the best matches, determined according to our logic, but there is no difference using `all_matches` with a threshold of `0.`. Re-open the issue if you need something more. It would be interesting to know what these sections contain.

```
best_matches %>% filter(match_code == "LA1844") %>% knitr::kable() %>% write_clip()
```

| borrower_section | match_section | score | borrower_code | borrower_year | borrower_state | match_code | match_year | match_state |
| :-- | :-- | --: | :-- | --: | :-- | :-- | --: | :-- |
| CA1850-000530 | LA1844-003280 | 0.2000000 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-001360 | LA1844-003100 | 0.1186441 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-001380 | LA1844-003120 | 0.1954023 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002700 | LA1844-005560 | 0.8571429 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002710 | LA1844-005570 | 0.3962264 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002720 | LA1844-005580 | 0.5789474 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002730 | LA1844-005590 | 0.3781513 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002740 | LA1844-005600 | 0.3630137 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002750 | LA1844-005610 | 0.2244898 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-002760 | LA1844-005620 | 0.6896552 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1850-003090 | LA1844-004880 | 0.4166667 | CA1850 | 1850 | CA | LA1844 | 1844 | LA |
| CA1858-007160 | LA1844-005990 | 0.1428571 | CA1858 | 1858 | CA | LA1844 | 1844 | LA |

**Comment by lmullen** [comment]
Here is one match:

> sections[["LA1844-005620"]] %>% content
> 663. The court shall decide summarily on such applications. 
> If a new trial be granted, the cause shall again be set on the
> docket ; and on the new trial the parties shall not be precluded
> from producing new proofs, on the ground of the same not having 
> been offered on the first trial.

**Comment by lmullen** [comment]
Another

> sections[["LA1844-005580"]] %>% content()
> 659. The party demanding a new trial, must set forth the
> ,grounds on which he rests his demand, and the same must be filed, 
> entered on the records of the court, and notified to the adverse
> party, i_n order that he may answer within the delay prescribed for 
> answenng.
