### ISSUE TITLE
Dissertation Visual #8: Spectrogram/Heat Map of NY1876

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#24]
Same query as number 6 and 7, but like Louisiana, the point is to show that no one borrows the later New York Code, the one that departs from the Field tradition.

**Comment by lmullen** [comment]
NY1879 borrows a lot from this code. That's not an interesting point, I assume, except to reinforce the point that NY1876 and NY1879 are a clean break from the Field code. Here is a list of the number of sections that each code borrows from NY1879:

```
best_matches %>% filter(match_code == "NY1876") %>% count(borrower_code) %>% arrange(desc(n)) %>% knitr::kable() %>% write_clip()
```

| borrower_code | n |
| :-- | --: |
| NY1879 | 1463 |
| MT1895 | 53 |
| CT1879 | 3 |
| OH1879 | 3 |
| ND1877 | 2 |
| AK1900 | 1 |
| AZ1887 | 1 |
| UT1884 | 1 |
| VA1893 | 1 |
| WY1886 | 1 |

And here is the number of times each section in NY1876 that is borrowed, is borrowed. Only those sections borrowed more than once.

```
best_matches %>% filter(match_code == "NY1876") %>% count(match_section) %>% arrange(desc(n)) %>% filter(n > 1) %>% knitr::kable() %>% write_clip()
```

| match_section | n |
| :-- | --: |
| NY1876-000800 | 3 |
| NY1876-004830 | 3 |
| NY1876-005350 | 3 |
| NY1876-005760 | 3 |
| NY1876-000600 | 2 |
| NY1876-000750 | 2 |
| NY1876-000760 | 2 |
| NY1876-000780 | 2 |
| NY1876-000790 | 2 |
| NY1876-000810 | 2 |
| NY1876-000820 | 2 |
| NY1876-000830 | 2 |
| NY1876-000840 | 2 |
| NY1876-000880 | 2 |
| NY1876-001560 | 2 |
| NY1876-001980 | 2 |
| NY1876-003840 | 2 |
| NY1876-004210 | 2 |
| NY1876-004220 | 2 |
| NY1876-004230 | 2 |
| NY1876-004370 | 2 |
| NY1876-004420 | 2 |
| NY1876-004430 | 2 |
| NY1876-004450 | 2 |
| NY1876-004860 | 2 |
| NY1876-004880 | 2 |
| NY1876-004890 | 2 |
| NY1876-004940 | 2 |
| NY1876-005110 | 2 |
| NY1876-005310 | 2 |
| NY1876-005330 | 2 |
| NY1876-005360 | 2 |
| NY1876-005380 | 2 |
| NY1876-005460 | 2 |
| NY1876-005480 | 2 |
| NY1876-005490 | 2 |
| NY1876-005580 | 2 |
| NY1876-005630 | 2 |
| NY1876-005640 | 2 |
| NY1876-006160 | 2 |
| NY1876-006250 | 2 |
| NY1876-006780 | 2 |
| NY1876-006790 | 2 |
| NY1876-007010 | 2 |
| NY1876-007430 | 2 |
| NY1876-007550 | 2 |
| NY1876-007650 | 2 |
| NY1876-008210 | 2 |
| NY1876-008370 | 2 |
| NY1876-008800 | 2 |
| NY1876-008870 | 2 |
| NY1876-010470 | 2 |
| NY1876-010920 | 2 |
| NY1876-011010 | 2 |
| NY1876-011020 | 2 |
| NY1876-011100 | 2 |
| NY1876-011200 | 2 |
| NY1876-011230 | 2 |
| NY1876-011350 | 2 |
| NY1876-011370 | 2 |
| NY1876-011380 | 2 |
| NY1876-011390 | 2 |
| NY1876-012390 | 2 |
| NY1876-012510 | 2 |
| NY1876-012530 | 2 |
| NY1876-012540 | 2 |
| NY1876-012560 | 2 |
| NY1876-012570 | 2 |
| NY1876-012610 | 2 |
| NY1876-012620 | 2 |
| NY1876-012670 | 2 |
| NY1876-012950 | 2 |
| NY1876-012990 | 2 |
| NY1876-013770 | 2 |
| NY1876-014630 | 2 |

**Comment by lmullen** [comment]
Those most borrowed sections:

> sections[["NY1876-000800"]] %>% content()
> 75. An attorney or counsellor, who violates either of
> the last two sections, is guilty of a misdemeanor; and, on
> conviction thereof, shall be punished accordingly, and must
> be removed from office by the supreme court.
> sections[["NY1876-004830"]] %>% content()
> 446. All persons having an interest in the subject of

the action, and in obtaining the judgment demanded, may
be joined as plaintifffs, except as otherwise expressly prescribed in this act.

> sections[["NY1876-005350"]] %>% content()
> 494. The plaintifff may demur to a counterclaim or a
> defense consisting of new matter, contained in the answer,
> on the ground that it is insufficient in law, upon the face

thereof.

> sections[["NY1876-005760"]] %>% content()
> 534. Where a cause of action, defense, or counterclaim,
> is founded upon an instrument for the payment of money
> only, the party may set forth a copy of the instrument, and
> state that there is due to him thereon, from the adverse
> party, a specified sum, which he claims. Such an allegation
> is equivalent to setting forth the instrument, according to
> its legal effect.

**Comment by lmullen** [comment]
```
spectrogram("MT1895", best_matches, white_list = 7)
```

<img width="740" alt="screenshot 2016-01-05 14 05 21" src="https://cloud.githubusercontent.com/assets/183672/12124781/63ebe854-b3b5-11e5-988c-6ec6d152ddb9.png">

```
spectrogram("NY1879", best_matches)
```

<img width="626" alt="screenshot 2016-01-05 14 06 06" src="https://cloud.githubusercontent.com/assets/183672/12124791/7aac1690-b3b5-11e5-81b6-36ed792d732e.png">

**Comment by lmullen** [comment]
Anything of interest here to make a visualization of?

**Comment by lmullen** [comment]
For good measure, borrowings in NY1876

```
spectrogram("NY1876", best_matches, white_list = 8)
```

<img width="802" alt="screenshot 2016-01-05 14 11 34" src="https://cloud.githubusercontent.com/assets/183672/12124913/44f8ffb2-b3b6-11e5-93c7-18a4127ff295.png">

**Comment by kfunk074** [comment]
Let's keep MT as another good illustration of splicing. Can you tell me what's in the "other" category? If it really is a grab bag, we can leave as is. If there's just one or two code accounting for most of those splotches, let's add them to the white line.

Let's also keep NY1876. Texas was definitely not consulted, so remove from ranking. And the 1879 image leads me to suspect a lot of these matches may be incidental because of shared topic (The Texas matches seem to confirm this suspicion). How high a Jaccard score are you inputting to count as a match in the general formula? .1? Try .25 and see if there's a dramatic difference.
