### ISSUE TITLE
Ranking Ties in Most Borrowed Sections

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#3]
When sections have the same Jaccard score, both are returned as a top match borrowing. For determining percentage of borrowed sections between codes, we want to discriminate between these ties and rank the most likely borrowing higher. So if 30% of a UT code appears borrowed from NV, and 2% from CA, and a given section has the same Jaccard score for both NV and CA, NV should count as the higher match.

**Comment by lmullen** [comment]
The dplyr documentation has a reference to fuzzy ties. That might be something useful.
