### ISSUE TITLE
Fix relative sizes of spectrograms

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#31]
Can we standardize the size? I note they all seem to have forty columns and variable rows depending on length of the code. I prefer the size that NC1868 and CO1868 are displaying at.

**Comment by lmullen** [comment]
Yes and no. They have a varying length do something has to be a different size. But I agree with what I think you're saying: the size of boxes should be constant, while the height of the image changes to accommodate the varying lengths of the codes. Will fix.

**Comment by lmullen** [comment]
This will depend on the document that they are embedded in more than the `spectrogram()` function, so I'm going to note this but close it.
