### ISSUE TITLE
Racial Exclusion Sections

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#32]
I've put a new subfolder on dropbox titled racial exclusions. From the clusters, I've pulled specific sections barring testimony by racial minorities.

Can you produce a list of every document in the sectioned folder that contains the roots negro OR indian OR china OR chinese OR mongol OR blood (just to make sure we capture them all despite OCR). I'll run that list against the sections I already pulled and see if any were ignored by the clustering approach.

**Comment by lmullen** [comment]
Also, Mongolian. Well, I guess Mongol catches that as a substring.

**Comment by lmullen** [comment]
List of section names in `racial-exclusions/list-of-racial-sections.txt` in Dropbox. Going to pull the text of those.

**Comment by lmullen** [comment]
There is a file `racial-exclusions/exclusion-sections.txt` which has the text of each section that contains the terms above. This file is currently ordered by year and then by code. There are probably a lot of sections that are not of interest. You can either give me a list of sections to delete or delete the relevant lines in `racial-exclusions/list-of-racial-sections.txt`, and then I'll re-run the script to get a cleaner document. Feel free to close the issue when you are satisfied.

**Comment by lmullen** [comment]
Any reason that `mulatto` and its derivatives would appear where `negro` does not?

**Comment by lmullen** [comment]
I think this is done, right? If not, please reopen.
