### ISSUE TITLE
Short sections.

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#7]
§ 114. All fictions
in pleading
are abolished.

Let's make sure we don't assume short sections are necessarily garbage and discard them. When I've finished cleaning up the section breaks, we should be able to filter out heading material (which will often be brief) without losing short but critical sections like the above.

**Comment by lmullen** [comment]
Are these sections currently being discarded? I'm only throwing way sections of fewer than six words, so that we can get two 5-grams per document, so a section like this should be retained.

**Comment by lmullen** [comment]
This specific section should be fine:

› ag -i "All fictions"                                                                1
DC1857-00001060.txt
1:All fictions in pleading are abolish ed.

DT1862-00001050.txt
1:All fictions in pleading are abolished.

IA1859-00001200.txt
5:mon eounte, general ieeuee, and all fictions are abolished, and hereafter

KS1868-00001150.txt
1:All fictions in pleadings are abolished.

NE1859-00000480.txt
372:114. All fictions

NE1866-00001360.txt
1:All fictions in pleadings are abolished. 1

OH1853-00001260.txt
1:All fictions in pleading are abolished.

OH1853extended-00001260.txt
1:All fictions in pleading are abolished.

OH1879-00002250.txt
2:all fictions therein are abolished; and the title of a cause shall not be

OK1891-00000080.txt
479:(4417) § 44. All fictions in pleading are abolished, and their:

WY1870-00001160.txt
6:SE6. 125. All fictions in pleadings are abolished.
