### ISSUE TITLE
Sectioning in OK1891

### ISSUE THREAD

**Issue by lmullen** [lmullen/civil-procedure-codes#8]
@kfunk074 Can you please take a look at OK1891 and tell me what is going on with the sections there? Some of them have this form:

> (4376) § 3. The only pleadings allowed are:
> First. The complaint by the plaintifff.
> Second. Demurrer and answer by the defendant.
> Third. The demurrer and reply by the plaintifff.
> Fourth. Demurrer to the reply.
> (4377) § 4. The first pleading on the part of the plaintifff is
> the complaint.

What is the number in parenthesis? Do we need to (a) strip them out or (b) add a different sectioning type?

**Comment by kfunk074** [comment]
Don't know what in particular is going on with Oklahoma, but this appears in several codes where a state incorporated a procedure code--usually enacted years earlier--into a larger, newer civil code or set of revised statutes. The legislature favors numbering all laws from 1 to n, but know that the profession has gotten used to referring to "Section 4" as shorthand for complaints. So they use both numbers. I'll resolve this when I clean up the sections.
